export const responseData = [
	{
		id: '1',
		label: 'Understanding Cancer',
		path: '/about-cancer/understanding',
		langcode: 'en',
		hasChildren: true,
		children: [
			{
				id: '1a1',
				label: 'What Is Cancer',
				path: '/about-cancer/understanding/what-is-cancer',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '1a2',
				label: 'Cancer Statistics',
				path: '/about-cancer/understanding/statistics',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '1a3',
				label: 'Cancer Disparities',
				path: '/about-cancer/understanding/disparities',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
		],
	},
	{
		id: '2',
		label: 'Causes & Prevention',
		path: '/about-cancer/causes-prevention',
		langcode: 'en',
		hasChildren: true,
		children: [
			{
				id: '2a1',
				label: 'Risk Factors',
				path: '/about-cancer/causes-prevention/risk',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '2a2',
				label: 'Genetics',
				path: '/about-cancer/causes-prevention/genetics',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '2a3',
				label: 'Cancer Prevention Overview',
				path: '/about-cancer/causes-prevention/patient-prevention-overview-pdq',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
		],
	},
	{
		id: '3',
		label: 'Screening',
		path: '/about-cancer/screening',
		langcode: 'en',
		hasChildren: true,
		children: [
			{
				id: '3a1',
				label: 'Cancer Screening Overview',
				path: '/about-cancer/screening/patient-screening-overview-pdq',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '3a2',
				label: 'Screening Tests',
				path: '/about-cancer/screening/screening-tests',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
		],
	},
	{
		id: '4',
		label: 'Diagnosis & Staging',
		path: '/about-cancer/diagnosis-staging',
		langcode: 'en',
		hasChildren: true,
		children: [
			{
				id: '4a1',
				label: 'Symptoms',
				path: '/about-cancer/diagnosis-staging/symptoms',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '4a2',
				label: 'Diagnosis',
				path: '/about-cancer/diagnosis-staging/diagnosis',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '4a3',
				label: 'Staging',
				path: '/about-cancer/diagnosis-staging/staging',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '4a4',
				label: 'Prognosis',
				path: '/about-cancer/diagnosis-staging/prognosis',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
		],
	},
	{
		id: '5',
		label: 'Treatment',
		path: '/about-cancer/treatment',
		langcode: 'en',
		hasChildren: true,
		children: [
			{
				id: '5a1',
				label: 'Types of Treatment',
				path: '/about-cancer/treatment/types',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '5a2',
				label: 'Side Effects',
				path: '/about-cancer/treatment/side-effects',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '5a3',
				label: 'Clinical Trials',
				path: '/about-cancer/treatment/clinical-trials',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '5a4',
				label: 'Cancer Drugs',
				path: '/about-cancer/treatment/drugs',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '5a5',
				label: 'Complementary & Alternative Medicine',
				path: '/about-cancer/treatment/cam',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
		],
	},
];

export const responseDataShort = [
	{
		id: '1',
		label: 'Understanding Cancer',
		path: '/about-cancer/understanding',
		langcode: 'en',
		hasChildren: true,
		children: [
			{
				id: '1a1',
				label: 'What Is Cancer',
				path: '/about-cancer/understanding/what-is-cancer',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '1a2',
				label: 'Cancer Statistics',
				path: '/about-cancer/understanding/statistics',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '1a3',
				label: 'Cancer Disparities',
				path: '/about-cancer/understanding/disparities',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
		],
	},
	{
		id: '2',
		label: 'Causes & Prevention',
		path: '/about-cancer/causes-prevention',
		langcode: 'en',
		hasChildren: true,
		children: [
			{
				id: '2a1',
				label: 'Risk Factors',
				path: '/about-cancer/causes-prevention/risk',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '2a2',
				label: 'Genetics',
				path: '/about-cancer/causes-prevention/genetics',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '2a3',
				label: 'Cancer Prevention Overview',
				path: '/about-cancer/causes-prevention/patient-prevention-overview-pdq',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
		],
	},
	{
		id: '3',
		label: 'Screening',
		path: '/about-cancer/screening',
		langcode: 'en',
		hasChildren: true,
		children: [
			{
				id: '3a1',
				label: 'Cancer Screening Overview',
				path: '/about-cancer/screening/patient-screening-overview-pdq',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '3a2',
				label: 'Screening Tests',
				path: '/about-cancer/screening/screening-tests',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
		],
	},
	{
		id: '4',
		label: 'Diagnosis & Staging',
		path: '/about-cancer/diagnosis-staging',
		langcode: 'en',
		hasChildren: true,
		children: [
			{
				id: '4a1',
				label: 'Symptoms',
				path: '/about-cancer/diagnosis-staging/symptoms',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '4a2',
				label: 'Diagnosis',
				path: '/about-cancer/diagnosis-staging/diagnosis',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '4a3',
				label: 'Staging',
				path: '/about-cancer/diagnosis-staging/staging',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
			{
				id: '4a4',
				label: 'Prognosis',
				path: '/about-cancer/diagnosis-staging/prognosis',
				langcode: 'en',
				hasChildren: false,
				children: [],
			},
		],
	},
];
