name: Generate Backstop Reference Images
on: workflow_dispatch
jobs:
  generate_images:
    name: Generate Images
    runs-on: ubuntu-latest
    services:
      apache:
        image: httpd:2.4
        ports:
          - 8080:80
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v3
      ## Setup node and npm caching.
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com
          scope: '@nciocpl'
      ## Override default lerna version
      - name: Install Lerna
        run: yarn global add lerna@6.6.2
      ## Bootstrap Lerna
      - name: Bootstrap Lerna
        run: lerna bootstrap -- --frozen-lockfile
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Storybook and Copy to dist
        run: yarn storybook:build && yarn storybook:copy
      - name: Copy built storybook to apache
        working-directory: ./dist/documentation-site/storybook
        run: |
          CONTAINER_ID=$(docker ps -q --filter "ancestor=httpd:2.4")
          docker cp . "$CONTAINER_ID:/usr/local/apache2/htdocs"
      ## Now generate the reference images
      - name: Run image generation
        working-directory: ./testing/ncids-css-testing
        run: node_modules/.bin/backstop reference --config='backstop.config.js' --docker
        env:
          CI: true
          BACKSTOP_BASE_URL: http://localhost:8080/
      - uses: actions/upload-artifact@v3
        name: Upload reference images
        with:
          name: backstopjs-reference
          path: /home/runner/work/ncids/ncids/testing/ncids-css-testing/.backstop/reference
